### ISSUE TITLE
Cards property not being populated

### ISSUE THREAD

**Issue by ghost** [eddywashere/node-stripe-membership-saas#10]
.

**Comment by eddywashere** [comment]
thanks! I'll check this out

**Comment by PokerCurve** [comment]
It works fine now that I switched to customer.sources instead:

var card = customer.sources.data[0];

**Comment by eddywashere** [comment]
Ah. I see. There were major api changes: https://stripe.com/docs/upgrades#2015-02-18

I'll create a pr to update. Thanks again for reporting this!

**Comment by flooie** [comment]
@cpustar can you explain a little more how you resolved it?

**Comment by benrlodge** [comment]
Thanks for working on this project - it's been a nice starting point. Any progress on this issue though? I just ran into it myself.

**Comment by eddywashere** [comment]
@benrlodge this should be fixed with #14

**Comment by benrlodge** [comment]
Thanks for the update. I ran into another error on the change - I'll comment on the PR.
